### ISSUE TITLE
Document code in liwc_etc

### ISSUE THREAD

**Issue by iangow** [iangow/se_features#1]
@danielacarrasco:

Code in `liwc_etc` provides a template of sorts.

For example, `liwc_run.py` calls `liwc_add.py` which uses functions in `liwc_functions.py`. I think it would make sense to add a little documentation explaining what the various pieces of code do (at a high level). This will make it easier to apply the "template" to calculating other features. Documentation would be quite short and basic (probably a `README.md` file in the `liwc_etc` directory.

**Comment by iangow** [comment]
@danielacarrasco it may be that this is already done. If the readme is correct and sufficiently describes the way the code runs, then I think we can close this issue. One thing that I noticed is a reference to `liwc_tmp`. This may be incorrect and require a simple fix to the readme.

**Comment by danielacarrasco** [comment]
yes, you are right. I just corrected it.

**Comment by danielacarrasco** [comment]
I'll read the README again and make sure it's all okay. I'll be closing it afterwards (probably tomorrow).

**Comment by danielacarrasco** [comment]
> I'll read the README again and make sure it's all okay. I'll be closing it afterwards (probably tomorrow).

It all looks good so I'll close this.
