### ISSUE TITLE
Run NER tagging

### ISSUE THREAD

**Issue by iangow** [iangow/se_features#13]
Code is found [here](https://github.com/iangow/se_features/tree/master/ner).

- [x] Delete material related to "Alternative 1: UChicago RCC".
- [x] References to schema `bs_linguistics` should be to `se_features`.
- [x] References to directory `proper_nouns` should be to `ner`.
- [x] Delete references to "Finance abbreviations".
- [x] Perhaps get the latest NER tagger and test that we can run it on the MCCGR server. 
- [x] Update instructions accordingly.

**Comment by Yvonne-Han** [comment]
> @Yvonne-Han I just reassigned this to you. Are we done with this?

@iangow I’ve ticked what is done so far. Among the tasks, I’m not too sure what the `Chicago RRC` part is about. 

Is this your new way of dealing with too many todos - by assigning someone else (i.e., me)? (Just joking 😄 I will take a look and reply to your other assignments/comments tomorrow).

**Comment by iangow** [comment]
Chicago RCC is referred to in the README, but I think the associated code has been removed. So the README might need to be adjusted.

**Comment by Yvonne-Han** [comment]
> Chicago RCC is referred to in the README, but I think the associated code has been removed. So the README might need to be adjusted.

I see. So it’s just updating README (and I will need to adjust it anyways for other updates so it should be quick. I thought I need to remove some real code so I was a little bit unsure).

**Comment by Yvonne-Han** [comment]
@iangow I've updated the READM, deleted materials related to Chicago RCC, and deleted/replaced the references as mentioned above (I also deleted one reference that is probably pointing to Anastasia's private repository - link [here](https://github.com/azakolyukina/bs_linguistics/blob/master/proper_nouns/README.md)). 

If there's nothing missing from the README, you can close this issue.

**Comment by iangow** [comment]
All good. I extracted a couple of quick-to-address issues so we can close this one.
