### ISSUE TITLE
Clean up LIWC regular expressions

### ISSUE THREAD

**Issue by iangow** [iangow/se_features#18]
Builds on iangow/se_features#17.

- [x] Treat `'` as word boundary.
- [x] Spaces should be fine as is.
- [x] Check handling of `-`. 
- [x] Remove `(` and `)` from phrases.
- [ ] Perhaps remove emoticons (will not appear in conference calls); perhaps keep them for a more general approach
- [x] Check handling of numbers.
- [x] Check spaces in the phrases that are in the dictionary

@Yvonne-Han Note that `regexp_matches` in R code below is a PostgreSQL [function](https://www.postgresql.org/docs/current/functions-matching.html).

 ``` r
library(dplyr, warn.conflicts = FALSE)
library(DBI)

pg <- dbConnect(RPostgres::Postgres(), bigint = "integer")

rs <- dbExecute(pg, "SET search_path TO se_features, streetevents")

liwc_2015 <- tbl(pg, "liwc_2015")

liwc_2015 %>%
    mutate(word = unnest(word_list)) %>%
    select(-word_list) %>%
    mutate(matches = regexp_matches(word, '[^a-z0-9\\*]+')) %>%
    mutate(match = unnest(matches)) %>% 
    count(match) %>%
    arrange(desc(n)) %>%
    print(n= Inf)
#> # Source:     lazy query [?? x 2]
#> # Database:   postgres [igow@10.101.13.99:5432/crsp]
#> # Ordered by: desc(n)
#>    match      n
#>    <chr>  <int>
#>  1 '        674
#>  2 -        105
#>  3 "\\("     44
#>  4 " "        6
#>  5 ":\\("     4
#>  6 ":\\)"     4
#>  7 "\\/"      4
#>  8 "\\):"     4
#>  9 "\\(:"     4
#> 10 ";\\)"     2
#> 11 "\\/:"     2
#> 12 "\\(;"     2
#> 13 ":\\/"     2
```

<sup>Created on 2019-07-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Yvonne-Han** [comment]
Solved by manually modifying the number category using the following code:

https://github.com/iangow/se_features/blob/d8d868701a1d927e2b12ceec472bcc23e27673a2/liwc_2015/liwc_functions.py#L33-L35
