### ISSUE TITLE
Convert functions to come from package.

### ISSUE THREAD

**Issue by iangow** [iangow/se_features#26]
@Yvonne-Han I want to simplify this package a bit and extract some of it from its current tight link with StreetEvents.

**Comment by iangow** [comment]
@Yvonne-Han So I made a new Python package for testing. You should be able to install it in your personal package library on this computer using the command line thus:

```
pip3 install ling_features --upgrade
```
Then I think we want to test it on each of the libraries. For example, 

https://github.com/iangow/se_features/blob/37a201fa92caeb521b1f048c30404bc4f8dcd7a5/fog_measure/fog_add.py#L7

could be replaced by 
```python
from fog_functions import fog
```
and then we might want to test it a little before moving along to testing other functions that I've converted there.

**Comment by iangow** [comment]
@Yvonne-Han Oops. I've updated the last comment.

**Comment by iangow** [comment]
@Yvonne-Han See [here](https://pypi.org/project/ling-features/#history) for more on the new Python package.

**Comment by Yvonne-Han** [comment]
@iangow I've successfully installed the package and this looks cool! 
Anything specific you would like to test? I've tried to play with it myself and I can see that I can use the `fog function` as below:

```python
In [9]: fog("Hello world!")
Out[9]: {'fog': 0.8, 'complex_words': 0, 'fog_words': 2, 'fog_sents': 1}
```

**Comment by iangow** [comment]
@Yvonne-Han [This](https://github.com/iangow/se_features/blob/90973c4c2b69ec3f66fdf1079bcb156da41ab8c4/fog_measure/fog_test.ipynb) is what I had in mind. The tweak to the code is in the commit just above the last one.

I will update StreetEvents so that there are files to process and then run the `fog_run.py` script. If you could do something similar for the functions available (e.g., tone) in the new package that would be great.

**Comment by iangow** [comment]
> then run the `fog_run.py` script.

Done. About 4000 files, I think.

**Comment by Yvonne-Han** [comment]
> @Yvonne-Han [This](https://github.com/iangow/se_features/blob/90973c4c2b69ec3f66fdf1079bcb156da41ab8c4/fog_measure/fog_test.ipynb) is what I had in mind. The tweak to the code is in the commit just above the last one.
> 
> I will update StreetEvents so that there are files to process and then run the `fog_run.py` script. If you could do something similar for the functions available (e.g., tone) in the new package that would be great.

Sure. I will do this for your other functions in the new package. From [here](https://github.com/iangow/ling_features) I can see that you've got functions in the new package for:
- [ ] **fog**: fog
- [ ] **tone**: tone_count
- [ ] **topic**: kls_domains_ind
- [ ] **word count**: word_count, number_count, sent_count,

**Comment by iangow** [comment]
Sounds good. Note that it's basically two things with the code (deleting code and pointing to the package), followed by a check, and then a run to update the data. You might use Python Notebooks like that one I add for the check.

**Comment by Yvonne-Han** [comment]
> Sounds good. Note that it's basically two things with the code (deleting code and pointing to the package), followed by a check, and then a run to update the data. You might use Python Notebooks like that one I add for the check.

I'm (1) doing checks in Jupyter Notebook before (2) deleting your original code & pointing to the package and (3) updating the data. See the updated to-do list above for the current progress. 

@iangow A few things that I want to double-check with you:
- tone: `tone_count`
  -  I compared the output of the `tone_count` function in the new package with `orig_data` but there seemed to be inconsistencies between the two. See commit 5bdc981c0a06477ff0f69e820834a256d52e31ec.
  - So, for now, I didn't update your python code and the `se_features.tone_measure` table.
- topic: `kls_domains_ind`
   - It might be a silly question to ask... but do we have a corresponding table in our database for this `topic` measure? 
   - I can't find one by looking browsing the `se_features` schema or by referring to the code in the `topic` [folder](https://github.com/iangow/se_features/tree/master/topic), so I don't know which table to use for the check...

**Comment by iangow** [comment]
Yes, `event_type=1` should not be there.

I think the table for "topic" should be `kls_domains`. You could adapt the code from the other folders, but you probably want `CREATE TABLE` functionality like that in the NER code if that isn't there already.

**Comment by iangow** [comment]
Yes, `event_type=1` should not be there.

I think the table for "topic" should be `kls_domains`. You could adapt the code from the other folders, but you probably want `CREATE TABLE` functionality like that in the NER code if that isn't there already.

Regarding the differences in the tone output, this might be due to differences in the dictionaries used. I think that the old dictionary is embedded in a PostgreSQL table (see old code). So it should be possible to compare the word lists. Let me know if you need help with that. If it's differences in word-lists, I think we'd drop the existing table and do it all again (and perhaps think of a way of doing some kind of version note for the word lists).

**Comment by iangow** [comment]
My previous comment probably implies three issues. So maybe make those for each one that seems big enough to be worth that effort.

**Comment by Yvonne-Han** [comment]
> My previous comment probably implies three issues. So maybe make those for each one that seems big enough to be worth that effort.

Sure. I guess the `event_type = 1` issue is a quick fix, so I will probably just make issues for the other two so that we can keep track of them.

**Comment by Yvonne-Han** [comment]
> Yes, event_type=1 should not be there.

Fixed with a quick commit here 79418573e69be97a533fbe62ba502967d36b3f09. 
I've also double-checked and confirmed that our current `se_features.word_counts` table is not affected as the table contains calls with `event_type != 1`. So it should be all good now!

``` r
library(dplyr, warn.conflicts = FALSE)
library(DBI)
library(reprex)

pg <- dbConnect(RPostgres::Postgres())
rs <- dbExecute(pg, "SET search_path TO streetevents, se_features")

calls <- tbl(pg, "calls")
word_counts <- tbl(pg, "word_counts")

word_counts %>% 
  select(file_name) %>%
  inner_join(calls) %>%
  group_by(event_type) %>%
  summarise(count(event_type))
#> Joining, by = "file_name"
#> # Source:   lazy query [?? x 2]
#> # Database: postgres [yanzih1@10.101.13.99:5432/crsp]
#>    event_type `count(event_type)`
#>         <int> <int64>            
#>  1          1 26756828           
#>  2          2     1976           
#>  3          5  1303323           
#>  4          7  2860295           
#>  5          8    79927           
#>  6         10     2299           
#>  7         11   272424           
#>  8         21     8953           
#>  9         22     7924           
#> 10         23        1           
#> # … with more rows
```

<sup>Created on 2020-05-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Yvonne-Han** [comment]
Two new issues are created as above : )

**Comment by Yvonne-Han** [comment]
> I think the table for "topic" should be kls_domains. 

@iangow Hmm... I tried but where can I find that table `kls_domains`? (Also, I checked the tables in `se_features` - I should know every one of them but none of them seem to be related to this).

```sql
crsp=> SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_name ~ 'kls';
 table_schema | table_name
--------------+------------
(0 rows)

crsp=> SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_name ~ 'domains';
    table_schema    | table_name
--------------------+------------
 information_schema | domains
(1 row)
```

**Comment by iangow** [comment]
> > I think the table for "topic" should be kls_domains.
> 
> @iangow Hmm... I tried but where can I find that table `kls_domains`? (Also, I checked the tables in `se_features` - I should know every one of them but none of them seem to be related to this).
> 
> ```sql
> crsp=> SELECT table_schema, table_name
> FROM information_schema.tables
> WHERE table_name ~ 'kls';
>  table_schema | table_name
> --------------+------------
> (0 rows)
> 
> crsp=> SELECT table_schema, table_name
> FROM information_schema.tables
> WHERE table_name ~ 'domains';
>     table_schema    | table_name
> --------------------+------------
>  information_schema | domains
> (1 row)
> ```

There is no such table. We'd need to add it. The code (say `run_kls.py` and `add_kls.py` following other features) should create the table if needed and give it the right data types, permissions, and indexes.

**Comment by iangow** [comment]
I think the remaining issues here have been picked up elsewhere.

**Comment by Yvonne-Han** [comment]
> > > I think the table for "topic" should be kls_domains.
> > 
> > 
> > @iangow Hmm... I tried but where can I find that table `kls_domains`? (Also, I checked the tables in `se_features` - I should know every one of them but none of them seem to be related to this).
> > ```sql
> > crsp=> SELECT table_schema, table_name
> > FROM information_schema.tables
> > WHERE table_name ~ 'kls';
> >  table_schema | table_name
> > --------------+------------
> > (0 rows)
> > 
> > crsp=> SELECT table_schema, table_name
> > FROM information_schema.tables
> > WHERE table_name ~ 'domains';
> >     table_schema    | table_name
> > --------------------+------------
> >  information_schema | domains
> > (1 row)
> > ```
> 
> There is no such table. We'd need to add it. The code (say `run_kls.py` and `add_kls.py` following other features) should create the table if needed and give it the right data types, permissions, and indexes.

Sure. I've already created an issue for this and it should be quick 😄
