### ISSUE TITLE
Test code for linguistic features 

### ISSUE THREAD

**Issue by iangow** [iangow/se_features#3]
@danielacarrasco

The folllowing should be done using Python 3. It may be helpful to document any packages, etc., that are needed to run the code. You may need to set environment variables `PGHOST` and `PGDATABASE` before running the code (see item 5 [here](https://github.com/iangow-public/wrds_pg)).

- Run [`make_sample_data.py`](https://github.com/iangow/streetevents_private/blob/master/linguistic_features/make_sample_data.py).
- Run code in [`test_tone_functions.ipynb`](https://github.com/iangow/streetevents_private/blob/master/linguistic_features/test_tone_functions.ipynb).
- Run code in [`test_perfomance_linguistic_features.ipynb`](https://github.com/iangow/streetevents_private/blob/master/linguistic_features/test_perfomance_linguistic_features.ipynb).

**Comment by danielacarrasco** [comment]
I am confused as to what host and database I should be using here. 

> * Run [`make_sample_data.py`](https://github.com/iangow/streetevents_private/blob/master/linguistic_features/make_sample_data.py).

This runs with no problem, using the given ('PGHOST', "localhost") and ('PGDATABASE', "postgres").

> * Run code in [`test_tone_functions.ipynb`](https://github.com/iangow/streetevents_private/blob/master/linguistic_features/test_tone_functions.ipynb).

This runs after installing some packages and downloading the data - I'm documenting this.

> * Run code in [`test_perfomance_linguistic_features.ipynb`](https://github.com/iangow/streetevents_private/blob/master/linguistic_features/test_perfomance_linguistic_features.ipynb).

I use the same host and database as before but I get the following error:

`OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "dcarrasco"
 (Background on this error at: http://sqlalche.me/e/e3q8)`

Is it possible I don't have access? 
I am using the Username and Password for PGHOST="10.101.13.99", PGDATABASE="crsp"

**Comment by iangow** [comment]
@danielacarrasco 

The only server you need to worry about for now is `PGHOST="10.101.13.99"`.

The way that SQLAlchemy picks up passwords is a bit opaque. The R packages I use will use the `PGPASSWORD` environment variable, but I'm not sure that SQLAlchemy (which is `psycopg2` under the hood, I guess) does so. You may need to set things up in `~/.pgpass` (this is easy on a Mac ... Google it, but feel free to ask if you have questions).

@bdcallen (Ben): How do you do this?

**Comment by iangow** [comment]
> Is it possible I don't have access?

I think you'd get a different error message in that case.

**Comment by danielacarrasco** [comment]
The server and user credentials were working. While running the program on my laptop (connected to the server)  I got disconnected and now every time I try to connect again I get the following:

> OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
 (Background on this error at: http://sqlalche.me/e/e3q8)

There's not much on the web, but I've tried different approaches and nothing seems to work. 
@iangow I was wondering if you can set me a folder on the server and I'll try to run it directly from there if that's possible.

**Comment by danielacarrasco** [comment]
> The server and user credentials were working. While running the program on my laptop (connected to the server) I got disconnected and now every time I try to connect again I get the following:
> 
> > OperationalError: (psycopg2.OperationalError) server closed the connection unexpectedly
> > This probably means the server terminated abnormally
> > before or while processing the request.
> > (Background on this error at: http://sqlalche.me/e/e3q8)
> 
> There's not much on the web, but I've tried different approaches and nothing seems to work.
> @iangow I was wondering if you can set me a folder on the server and I'll try to run it directly from there if that's possible.

hi @iangow , I'm still getting the same issue. I even uninstalled psycopg2 and installed it again and keep getting the same error message. Is it possible to get a home directory in the server? thanks!

**Comment by iangow** [comment]
@danielacarrasco I set up a login ID `dcarrasco` for you (same ID and password as you've been using for PostgreSQL). So you can log in:

```
ssh -L 8891:localhost:8891 dcarrasco@10.101.13.99
```
and then 

```
jupyter-notebook --port 8891
```
and then you will get a URL (something like `http://localhost:8888/?token=eed637405cbf4402bd4cdc8abd51253c79cd2a83b121ae1b`) that you can paste into your browser. This will give you access to a Jupyter notebook running on the server.

Note that it may be helpful to `git clone` the repositories your using onto the server. There are a few details to handle here (e.g., setting up SSH keys), but nothing too difficult.
