### ISSUE TITLE
Tell users about table relocation

### ISSUE THREAD

**Issue by iangow** [iangow/se_features#32]
@Yvonne-Han @MalihaChowdhury @yuchenliu4 Just FYI, I moved various link tables from `streetevents` to `se_links` in the MCCGR database. I'm not sure if you're using these at all (they are a bit of a mess and probably out of date) ... so just in case you're looking for them.

**Comment by yuchenliu4** [comment]
Hi Ian,

I have attached a brief summary of the regressions that I’ve done for tomorrow’s meeting.

Regards,
Yuchen

On 21 May 2020, at 12:08 pm, Ian Gow <notifications@github.com<mailto:notifications@github.com>> wrote:



Closed #32<https://github.com/iangow/se_features/issues/32>.
