### ISSUE TITLE
Sort out LIWC apostrophes

### ISSUE THREAD

**Issue by Yvonne-Han** [iangow/se_features#34]
I have to deal with apostrophes again as I believe it is causing some (or maybe all) of the differences between `liwc_orig` and `liwc_alt`.

> Note that one needs to be care with `'`, as there's a "curly" version of that character that might be treated differently (and my regular expression code may swap out the curly one for the "straight" one; there would be a separate line for that in the code). This may cause the apparent inconsistency.

_Originally posted by @iangow in https://github.com/iangow/se_features/issues/18#issuecomment-517072302_

> BTW, I think this is the line that converts "curly" apostrophes:

https://github.com/iangow/se_features/blob/32e2db2660f506265c890fd7286ae06a9371b864/liwc_2015/liwc_functions.py#L39

_Originally posted by @iangow in https://github.com/iangow/se_features/issues/18#issuecomment-517086556_

**Comment by iangow** [comment]
OK. I think `u'\u2019'` may be *just* one of the curly versions. So you may need to inspect the data more closely. Do you have a sample "utterance" (`file_name`, `speaker_number`, etc.) that's causing problems?

**Comment by Yvonne-Han** [comment]
> OK. I think u'\u2019' may be just one of the curly versions. So you may need to inspect the data more closely.

I see. I will take a closer look at this (this is so confusing...)!

> Do you have a sample "utterance" (file_name, speaker_number, etc.) that's causing problems?

I don't have it at the moment as I used some other texts to detect the errors and here's the text that got me the difference:

Text: "we’re"
`liwc_orig`: Verb: 1, We: 1
`liwc_alt`: Verb: 0, We: 1

Text: "we're"
`liwc_orig`: Verb: 1, We: 1
`liwc_alt`: Verb: 0, We: 1

@iangow I will go get some other samples (involving this issue) soon so that we can have a better idea of what's going on. Let me play with it first and get back to you.

**Comment by Yvonne-Han** [comment]
Punctuations that look like apostrophes:
- [ ] 0027 '  apostrophe
- [ ] 02BB ʻ  modifier letter turned comma
- [ ] 02BC ʼ  modifier letter apostrophe
- [ ] 2018 ‘ left single quotation mark
- [ ] 2019 ’ right single quotation mark
- [ ] 275B ❛  heavy single turned comma quotation mark ornament
- [ ] 275C ❜  heavy single comma quotation mark ornament
- [ ] 201A ‚ single low-9 quotation mark
- [ ] 201B ‛ single high-reversed-9 quotation mark
- [ ] 02BD ʽ  modifier letter reversed comma
- [ ] 2032 ′ prime
- [ ] 00B4 ´  acute accent
- [ ] 02B9 ʹ  modifier letter prime
- [ ] 2035 ‵ reversed prime

**Comment by Yvonne-Han** [comment]
![image](https://user-images.githubusercontent.com/53167984/83755095-63f9ed80-a6b0-11ea-95d3-2b1d9136a513.png)

**Comment by Yvonne-Han** [comment]
This should be everything related to apostrophes (hopefully) so I'm closing this now.

**Comment by iangow** [comment]
To close this properly, you should have some (previously) problematic text where the issue is (or appears to be) curly apostrophes and then confirm that now the LIWC software and our Python function gives the same results. Do you have a sample of problematic text? Or is it just these `.txt` files?

**Comment by Yvonne-Han** [comment]
> To close this properly, you should have some (previously) problematic text where the issue is (or appears to be) curly apostrophes and then confirm that now the LIWC software and our Python function gives the same results.

Yes I did compare the results of LIWC software and my code (in notebook) and confirmed that they are the same now. (I’m sorry that I forgot to post the notebook here...)

>  Do you have a sample of problematic text? Or is it just these .txt files?

No it’s just these .txt files (with file names indicating the type of punctuation being tested).
