### ISSUE TITLE
Sort out LIWC regex wildcards

### ISSUE THREAD

**Issue by Yvonne-Han** [iangow/se_features#35]
See below for an example. 

Text: """Victor's."
`liwc_orig`: Drives: 1, Achieve: 1, Reward: 1, Power: 1
`liwc_alt`: Drives: 0, Achieve: 0, Reward: 0, Power: 0

I went back and checked the word lists, and found that `victor*` is a word in all of the four categories mentioned above. So I guess the issue here is `liwc_orig` treats `victor's` as a match while `liwc_alt` does not). 

@iangow I guess this is the right line of code to look at?
https://github.com/iangow/se_features/blob/cd81362fae464abb51c4444489fa1579b38c69fc/liwc_2015/liwc_functions.py#L27

**Comment by Yvonne-Han** [comment]
> I'm thinking of doing this at the moment:
> 
> ```python
> mod_word_list[cat] = [re.sub('\*(?:\s*$)?', "(')?[a-z]*", word.lower()) 
> ```

This doesn't work for the following test case:

Text: """Victoria's"
liwc_orig: Drives: 1, Achieve: 1, Reward: 1, Power: 1
liwc_alt: Drives: 0, Achieve: 0, Reward: 0, Power: 0

**Comment by Yvonne-Han** [comment]
It seems that the wildcard in LIWC also includes numbers:

One example: (Note that `pc*` is in category `Work`)
Text: """pcsk9"""
liwc_orig: Work: 1
liwc_alt: Work: 0

Another example: (Note that `5*` is in category `Number`)

Text: """5x15"""
liwc_orig: Number: 1
liwc_alt: Number: 0

**Comment by Yvonne-Han** [comment]
Solution: 
> ```python
> mod_word_list[cat] = [re.sub('\*(?:\s*$)?', "[a-z0-9]*(')?[a-z0-9]*", word.lower()) 
> ```

**Comment by iangow** [comment]
@Yvonne-Han I guess LIWC contains a lot of nonsense. But I guess it's cleaner to just match what it does. Tweaks and improvements would be a different project.

**Comment by Yvonne-Han** [comment]
> @Yvonne-Han I guess LIWC contains a lot of nonsense. But I guess it's cleaner to just match what it does. Tweaks and improvements would be a different project.

Yes indeed. I've compared my `liwc_alt` with the original LIWC on some random texts and so far I think the results are quite okay. So I will probably wrap it up these days.
