### ISSUE TITLE
Create code to run fog function.

### ISSUE THREAD

**Issue by iangow** [iangow/se_features#4]
Related to 
https://github.com/azakolyukina/bs_linguistics/issues/48

**Comment by iangow** [comment]
@danielacarrasco I have assigned this task to you, but it may not make much sense, as I need to explain it better.

You initial tasks all relate to StreetEvents, a database of [conference calls](https://www.investopedia.com/small-business/what-is-an-earnings-conference-call/). I am trying to clean up a mess of code spread across a number of repositories. The vision is that the code will end up in three repositories:

- `se_core`: This is code to process the XML files we get from StreetEvents and create three *core* database tables.
- `streetevents` (aka `streetevents_private`): This contains a mess of code, but the plan is for this to merely contain code that links StreetEvents to other database or does work using the three core tables to create other tables.
- `se_features`: This will be the location for code to create "linguistic features" from StreetEvents data.

I think it may make sense to start with issues related to `se_features`, then do some work on `se_core`, then clean up `streetevents`. Don't worry, I will help in identifying and sequencing the tasks.

For your reference, [this](https://github.com/issues?utf8=✓&q=is%3Aopen+is%3Aissue+assignee%3Adanielacarrasco) is a list of the tasks assigned to you.

**Comment by iangow** [comment]
Here is a Perl function:

```perl
AS $function$
    use Encode qw(encode_utf8);
    use Lingua::EN::Fathom;
    use Lingua::EN::Sentence qw( get_sentences add_acronyms );

    if (defined($_[0])) {
        my $the_text = encode_utf8($_[0]);

        my $text = new Lingua::EN::Fathom;
        $text->analyse_block($the_text);
        $num_words = $text->num_words;
        $percent_complex = $text->percent_complex_words;

        my $sentences=get_sentences($the_text);   ## Get the sentences.
        $num_sentences =@$sentences;
        if ($num_sentences > 0) {
            $fog = 0.4 * ($num_words/$num_sentences + $percent_complex);
        }

        return($fog);
    }

$function$
```

The goal is to create a Python function that does the same thing.

The elements needed are:
- Number of words.
- Number of sentences.
- Number of works with three or more syllables.

For number of words, I think [this](https://stackoverflow.com/questions/10677020/real-word-count-in-nltk) may help. For number of sentences, I think `sent_tokenize` from NLTK would work. I have code for the number of syllables somewhere.

**Comment by iangow** [comment]
@danielacarrasco this might be a good one to work on next. Some details are in the issue r4ferred to in the first comment above.

**Comment by danielacarrasco** [comment]
_Update_

I am working on this function. I have a basic model but haven't been able to add it to the table (gives the following error)

`sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "fog" of relation "word_counts" does not exist`

I've added the following to `word_count_add.py`

`speaker_data['fog'] = speaker_data['speaker_text'].apply(fog_measure)`

and modified `word_count_run.py` accordingly

(fog_measure is defined in `word_count_functions.py` and seems to work. The problem is adding it to the table "speaker_data.word_counts")

I deleted a few tables because otherwise running `./word_count_run.py` wasn't doing anything as the table "speaker_data" was up to date. My guess is that there's an issue with having part of the table without that "fog" function and part with it. 

I'm thinking about producing a new table, say "speaker_data.word_counts2", but that's probably not the best option resources and time-wise

**Comment by iangow** [comment]
It will need to be a different table, say `fog`. The `word_counts` table is for word counts (code you ran last week). If you deleted the table, we need to regenerate it by running that code.

**Comment by iangow** [comment]
And it will need separate code, e.g., `fog_add.py`. 

OR

We could have one larger table containing multiple features. But, yes, this would mean starting from scratch for all features unless the code were substantially modified. I think it might be simpler just to have a separate table for each set of features. It is easy to combine them later.

**Comment by iangow** [comment]
@danielacarrasco 

I think it probably makes sense to put code for different features in different directories (e.g., code for "fog" should go in `fog`). I guess the `liwc_etc` directory should just contain LIWC-related code and the word count--related code should go in (say) `word_count`.

Note that I fixed an [issue](https://github.com/iangow/se_core/commit/90c29c933f885087bb9b549cca29193d78725a0f) with timestamps in the underlying StreetEvents data and ran the LIWC code again. I am running the word-count code now. Once that's done, I will make an issue related to moving the word-count code into its own directory.

**Comment by danielacarrasco** [comment]
Yes, it makes sense. I actually created the scripts with a similar structure for the fog measure: fog_run.py, fog_functions.py, and fog_add.py. I can move them to their own directory when I commit the changes.

**Comment by iangow** [comment]
OK. Please push code frequently just so it's easier to see we're making progress.

I don't think I've committed code here recently, but if you are told that you need to pull upstream changes before pushing your code, the best thing to do is 

```
git pull --rebase=preserve
git push
```

If you have unstaged changes, you might do 

```
git stash
git pull --rebase=preserve
git push
git stash apply
```
This keeps development on one line and avoids merge commits.

With regard to `se_features.fog`, it may make sense to `DROP TABLE se_features.fog` before running all the code given the changes to the data in `streetevents` tables. (I've already regenerated  `se_features.liwc` and `se_features.word_counts`.)

**Comment by danielacarrasco** [comment]
I realised the function word_count from `word_count_function.py` does not remove punctuation (i.e., it counts them as another word). I assume it doesn't make a big difference, but is it okay if I change that?
