### ISSUE TITLE
Create tone measure

### ISSUE THREAD

**Issue by iangow** [iangow/se_features#5]
This is the same issue as https://github.com/azakolyukina/bs_linguistics/issues/49, but let's work on and discuss the issue here. I will add more detailed instructions soon.

**Comment by iangow** [comment]
@danielacarrasco 

One step of this process will be getting the list of words for each tone category. The following R code does this ... but we will probably want to get the data into a form that can be used in Python (I added the last couple of lines to this end).

```r
category <- c("positive", "negative", "uncertainty",
                "litigious", "modal_strong", "modal_weak")

base_url <- "http://www3.nd.edu/~mcdonald/Data/Finance_Word_Lists"

url <- file.path(base_url,
                 c("LoughranMcDonald_Positive.csv",
                   "LoughranMcDonald_Negative.csv",
                   "LoughranMcDonald_Uncertainty.csv",
                   "LoughranMcDonald_Litigious.csv",
                   "LoughranMcDonald_ModalStrong.csv",
                   "LoughranMcDonald_ModalWeak.csv"))

df <- data.frame(category, url, stringsAsFactors=FALSE)

getWords <- function(url) {
    words <- read.csv(url, as.is=TRUE)
    paste(words[,1], collapse=",")
}
df$words <- unlist(lapply(df$url, getWords))

library(readr)
write_csv(df, path = "lm_words.csv")
```

**Comment by iangow** [comment]
```python
import pandas as pd
```


```python
df = pd.read_csv("lm_words.csv")
```


```python
df
```




<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>category</th>
      <th>url</th>
      <th>words</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>positive</td>
      <td>http://www3.nd.edu/~mcdonald/Data/Finance_Word...</td>
      <td>ABUNDANCE,ABUNDANT,ACCLAIMED,ACCOMPLISH,ACCOMP...</td>
    </tr>
    <tr>
      <th>1</th>
      <td>negative</td>
      <td>http://www3.nd.edu/~mcdonald/Data/Finance_Word...</td>
      <td>ABANDONED,ABANDONING,ABANDONMENT,ABANDONMENTS,...</td>
    </tr>
    <tr>
      <th>2</th>
      <td>uncertainty</td>
      <td>http://www3.nd.edu/~mcdonald/Data/Finance_Word...</td>
      <td>ABEYANCES,ALMOST,ALTERATION,ALTERATIONS,AMBIGU...</td>
    </tr>
    <tr>
      <th>3</th>
      <td>litigious</td>
      <td>http://www3.nd.edu/~mcdonald/Data/Finance_Word...</td>
      <td>ABROGATE,ABROGATED,ABROGATES,ABROGATING,ABROGA...</td>
    </tr>
    <tr>
      <th>4</th>
      <td>modal_strong</td>
      <td>http://www3.nd.edu/~mcdonald/Data/Finance_Word...</td>
      <td>BEST,CLEARLY,DEFINITELY,DEFINITIVELY,HIGHEST,L...</td>
    </tr>
    <tr>
      <th>5</th>
      <td>modal_weak</td>
      <td>http://www3.nd.edu/~mcdonald/Data/Finance_Word...</td>
      <td>APPEARED,APPEARING,APPEARS,CONCEIVABLE,COULD,D...</td>
    </tr>
  </tbody>
</table>
</div>




```python
import re

categories = [key for key in regex_dict.keys()]

def make_regex(words):
    word_list = words.lower().split(",")
    regex_text = '\\b(?:' + '|'.join(word_list) + ')\\b'
    regex = re.compile(regex_text)
    return regex
 
regex_dict = { cat: make_regex(df['words'][df['category'] == cat].iloc[0]) for cat in categories}
```


```python
import json 

def tone_count(the_text):

    # rest of function
    """Function to return number of matches in a category in a text"""
    text = the_text.lower()
    the_dict = {category: len(re.findall(regex_dict[category], text)) for category in categories}
    return json.dumps(the_dict)
```


```python
some_text = """I agree that my solution is more complex.
    But in part that’s because it’s a more complete solution. 
    One has to download and process the data from Bill MacDonald (“see his website for download” 
    implies undocumented steps in the process). 
    Then one has to organize and perhaps process the text so it can be fed to the Python function. 
    Finally, one needs to handle the output.

    I think the first step on my site could be done in Python (rather than R … my decision
    to use R is more a reflection of my comparative advantage in R than anything inherent to Python).
    And the second step could be done without PostgreSQL (especially if the first step is done in Python).
    I think a “pure Python” approach would be more elegant than what I have, at least as a code illustration."""

```


```python
tone_count(some_text)
```




    '{"positive": 1, "negative": 1, "uncertainty": 4, "litigious": 0, "modal_strong": 0, "modal_weak": 3}'

**Comment by iangow** [comment]
So I think the task is to make a `.py` file (say `tone_functions.py` that one can use by saying

```python
from tone_functions import tone_count
```

I think there should be something like the following as a kind of test:

```python
if __name__=="__main__":
    some_text = [see above]
    print(tone_count(some_text))
```

**Comment by iangow** [comment]
Note that "test text" was grabbed from [here](http://www.kaikaichen.com/?p=399). I just searched "tone python" or something like that.

**Comment by danielacarrasco** [comment]
`ProgrammingError: (psycopg2.ProgrammingError) permission denied for schema bs_linguistics`

I get that error. Is it the same problem we had with linguistic_features (i.e. just a matter of access)?

**Comment by iangow** [comment]
@danielacarrasco 

This is very similar to #9. I think we should create a folder `tone` with functions like what you made for #9 and then run it.

It might be easiest to start with the R code above and import the CSV file that creates. Later on, it should be easy to replace the R code with Python code and perhaps skip the creation of the CSV entirely.

**Comment by danielacarrasco** [comment]
I am running the code at the moment. I have already generated ~100000 tables at the moment. I modified the code following what you did with the fog tables. 
It would be great if you can have a look at them and let me know if they are ready. As soon as they are, I'll be starting with the ML.

**Comment by iangow** [comment]
The output looks good.
