### ISSUE TITLE
Identify and move tables related to this repository

### ISSUE THREAD

**Issue by iangow** [iangow/se_features#6]
@danielacarrasco 

We need to move tables from the database schema `bs_linguistics` to `se_features`.

Two steps:

1. Move tables using SQL (`ALTER TABLE` …).
2. Update code to reflect change in location.

**Comment by iangow** [comment]
This [search](https://github.com/iangow/se_features/search?q=bs_linguistics&unscoped_q=bs_linguistics) may be helpful.

**Comment by danielacarrasco** [comment]
The tables from bs_linguistics are:
> 
>      Schema     |      Name       | Type  |     Owner      
> ----------------+-----------------+-------+----------------
>  bs_linguistics | liwc            | table | bs_linguistics
>  bs_linguistics | liwc_old        | table | bs_linguistics
>  bs_linguistics | ner_class_alt_4 | table | igow
>  bs_linguistics | ner_class_alt_7 | table | igow
>  bs_linguistics | temp_prod       | table | igow
>  bs_linguistics | word_counts     | table | bs_linguistics
>  bs_linguistics | word_list       | table | bs_linguistics
> 

I've checked the code and the ones that seem to be used are:
- liwc
- word_counts
- word_list

Should I copy all of them or just those 3?

**Comment by iangow** [comment]
Just those three for now.

**Comment by danielacarrasco** [comment]
There is already a table named `word_counts` in `se_features`. I renamed it as `word_counts_old` and tried to copy the table from `bs_linguistics` with
`ALTER TABLE bs_linguistics.word_counts SET SCHEMA se_features;`

 but I get the error:
`ERROR:  relation "word_counts_pkey" already exists in schema "se_features"`

Can I delete `se_features.word_counts`?

PS: Is there any way you can grant me Admin access to the Mac in the office? I'm working here but din't have admin access.

**Comment by iangow** [comment]
Hmm. Yes. But I don’t recall how. Elisa knows ...

**Comment by iangow** [comment]
You could use the Linux box unless Ben is using it.

**Comment by iangow** [comment]
You could rename the `word_counts_pkey` relation ...

**Comment by danielacarrasco** [comment]
> Hmm. Yes. But I don’t recall how. Elisa knows ...

Elisa emailed me about this. It's solved now.



> You could rename the `word_counts_pkey` relation ...

Okay, I did that and had to rename the indexes as well. 

The 3 tables are now copied and the code has been changed.
