### ISSUE TITLE
Update LIWC data

### ISSUE THREAD

**Issue by iangow** [iangow/se_features#7]
Do #6, then do this. Critical step will be documenting the update steps, so that it is easy to do going forward.

**Comment by iangow** [comment]
Relevant code should be [here](https://github.com/iangow/se_features/tree/master/liwc_etc).

**Comment by danielacarrasco** [comment]
Not sure if this is what you meant, but I tested the code from `liwc_etc` following the instructions from the README and I think it's working. I ran `./word_count_run.py` and `./liwc_run.py` and this was printed in the terminal after each one.
`n_files: 4404`

Should I start with the next issues?

**Comment by iangow** [comment]
It should be that if you run it again `n_files: 0` (or nothing) is printed. It may indeed be as simple as what you’ve done.

**Comment by danielacarrasco** [comment]
Yes, that's what I get when I run it again, `n_files: 0`
